sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dipbhakta007/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dsipbhakta007/docker-react npm run test