sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dipbhakta007/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -v /app/node_modules -v $(pwd):/app dipbhakta007/docker-react npm run test